/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as AuthenticatedReputationRouteImport } from './routes/_authenticated/reputation'
import { Route as AuthenticatedPredictiveRouteImport } from './routes/_authenticated/predictive'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReputationRoute = AuthenticatedReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPredictiveRoute = AuthenticatedPredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/content': typeof AuthenticatedContentRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/predictive': typeof AuthenticatedPredictiveRoute
  '/reputation': typeof AuthenticatedReputationRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/content': typeof AuthenticatedContentRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/predictive': typeof AuthenticatedPredictiveRoute
  '/reputation': typeof AuthenticatedReputationRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/agency': typeof AuthenticatedAgencyRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/predictive': typeof AuthenticatedPredictiveRoute
  '/_authenticated/reputation': typeof AuthenticatedReputationRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ads'
    | '/agency'
    | '/analytics'
    | '/content'
    | '/copilot'
    | '/dashboard'
    | '/email'
    | '/onboarding'
    | '/predictive'
    | '/reputation'
    | '/seo'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ads'
    | '/agency'
    | '/analytics'
    | '/content'
    | '/copilot'
    | '/dashboard'
    | '/email'
    | '/onboarding'
    | '/predictive'
    | '/reputation'
    | '/seo'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ads'
    | '/_authenticated/agency'
    | '/_authenticated/analytics'
    | '/_authenticated/content'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/email'
    | '/_authenticated/onboarding'
    | '/_authenticated/predictive'
    | '/_authenticated/reputation'
    | '/_authenticated/seo'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reputation': {
      id: '/_authenticated/reputation'
      path: '/reputation'
      fullPath: '/reputation'
      preLoaderRoute: typeof AuthenticatedReputationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predictive': {
      id: '/_authenticated/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof AuthenticatedPredictiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPredictiveRoute: typeof AuthenticatedPredictiveRoute
  AuthenticatedReputationRoute: typeof AuthenticatedReputationRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedAgencyRoute: AuthenticatedAgencyRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPredictiveRoute: AuthenticatedPredictiveRoute,
  AuthenticatedReputationRoute: AuthenticatedReputationRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
